FROM fedora:44

RUN dnf install -y --refresh --nogpgcheck \
    gcc-c++ \
    cmake \
    git \
    make \
    ninja-build \
    vulkan-loader-devel \
    vulkan-headers \
    glslc \
    libshaderc-devel \
    spirv-headers-devel \
    spirv-tools \
    spirv-tools-devel \
    vulkan-tools \
    && dnf clean all

COPY scripts/build-llama.sh /usr/bin/build-llama
COPY scripts/build-llama-vulkan.sh /usr/bin/build-llama-vulkan
RUN chmod +x /usr/bin/build-llama /usr/bin/build-llama-vulkan

WORKDIR /root
CMD ["/usr/bin/build-llama"]
